// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddProduct(arg1) {
  return window['go']['main']['App']['AddProduct'](arg1);
}

export function AddStockItem(arg1) {
  return window['go']['main']['App']['AddStockItem'](arg1);
}

export function CreateOrder(arg1) {
  return window['go']['main']['App']['CreateOrder'](arg1);
}

export function DatabaseStatus() {
  return window['go']['main']['App']['DatabaseStatus']();
}

export function DeleteOrder(arg1) {
  return window['go']['main']['App']['DeleteOrder'](arg1);
}

export function DeleteProduct(arg1) {
  return window['go']['main']['App']['DeleteProduct'](arg1);
}

export function DeleteStockItem(arg1) {
  return window['go']['main']['App']['DeleteStockItem'](arg1);
}

export function GetCurrentTime() {
  return window['go']['main']['App']['GetCurrentTime']();
}

export function GetOrders() {
  return window['go']['main']['App']['GetOrders']();
}

export function GetProductByID(arg1) {
  return window['go']['main']['App']['GetProductByID'](arg1);
}

export function GetProducts() {
  return window['go']['main']['App']['GetProducts']();
}

export function GetStockItems() {
  return window['go']['main']['App']['GetStockItems']();
}

export function UpdateOrderStatus(arg1, arg2) {
  return window['go']['main']['App']['UpdateOrderStatus'](arg1, arg2);
}

export function UpdateProduct(arg1) {
  return window['go']['main']['App']['UpdateProduct'](arg1);
}

export function UpdateStockItem(arg1) {
  return window['go']['main']['App']['UpdateStockItem'](arg1);
}
