// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AddProduct(arg1:main.Product):Promise<boolean>;

export function AddStockItem(arg1:main.StockItem):Promise<main.StockItem>;

export function CreateOrder(arg1:any):Promise<boolean>;

export function DatabaseStatus():Promise<string>;

export function DeleteOrder(arg1:string):Promise<boolean>;

export function DeleteProduct(arg1:string):Promise<boolean>;

export function DeleteStockItem(arg1:string):Promise<boolean>;

export function GetCurrentTime():Promise<string>;

export function GetOrders():Promise<Array<main.Order>>;

export function GetProductByID(arg1:string):Promise<main.Product>;

export function GetProducts():Promise<Array<main.Product>>;

export function GetStockItems():Promise<Array<main.StockItem>>;

export function UpdateOrderStatus(arg1:string,arg2:string):Promise<boolean>;

export function UpdateProduct(arg1:main.Product):Promise<boolean>;

export function UpdateStockItem(arg1:main.StockItem):Promise<boolean>;
